### PR TITLE
Admin page "Create WorkSpace"

### PR DESCRIPTION
**Pull request by Nonnyss**
just test

### CODE REVIEW

**Comment by Nonnyss** [comment]
working on it ja

**Comment by Nonnyss** [comment]
add the useContext so the user can preview the edit in real time

**Comment by Nonnyss** [comment]
aye review me pls

**Comment by Nonnyss** [comment]
ayeee

**Comment by Nonnyss** [comment]
u here me

**Review by thepbordin — CHANGES_REQUESTED** [review]
some dependencies are missing so nextjs can't perform the production build please fix

**Comment by Nonnyss** [comment]
Change liaw Ja

**Pull request merged**
